//! T-103 — code-index benchmark gate (REQ-CK-002).
//!
//! Cold-indexes generated fixture repos at 10k and 100k LOC (Rust + Python,
//! the MVP language scope REQ-CK-001) through the REAL L1-L4 pipeline
//! (`OkfIndex::index_project`: okf-rs parse/analyze → bundle → L2 mirror →
//! L3 graph → L4 summary). The gate reports `index_ms` against the
//! REQ-CK-002 budgets: 10k LOC < 2 s, 100k LOC 10-30 s.
//!
//! The measurement is an explicit wall-clock timing (the crate's own
//! `IndexReport.duration_ms`) — criterion's sampling machinery would
//! re-run a 10-30 s op 100 times. Criterion is still used to report the
//! L4 overview latency (REQ-CK-003 "~100 ms order of magnitude").
//!
//! Fixture size: `MEMENTO_BENCH_LOC` (default 10_000). `scripts/bench.sh`
//! runs it at both reference sizes.

use std::path::Path;
use std::time::Instant;

use criterion::{Criterion, criterion_group, criterion_main};
use memento_okf::OkfIndex;
use memento_ports::knowledge::KnowledgePort;
use memento_testkit::TempStore;
use serde_json::json;

fn bench_loc() -> usize {
    std::env::var("MEMENTO_BENCH_LOC")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(10_000)
}

/// One gate line for `scripts/bench.sh`.
fn report(key: &str, value: serde_json::Value) {
    println!("MEMBENCH {key} {value}");
}

/// Write a deterministic mixed repo (70% Rust / 30% Python by LOC).
///
/// The fixture mimics realistic code density (~10 LOC per Rust function,
/// ~8 per Python function) — a real 10k-LOC repo holds ~700-1000 functions,
/// NOT the 2k+ a 4-LOC-per-function template would produce. The analyzer's
/// cost is per-concept, so fixture density must match reality or the gate
/// measures a synthetic worst case.
///
/// Every function calls the next one, so the analyzer resolves a real call
/// chain (graph edges). Returns (rust_loc, python_loc) actually written —
/// the templates are line-exact: Rust = 10 lines/function, Python = 8.
fn write_fixture(root: &Path, loc: usize) -> (usize, usize) {
    let rust_loc = loc * 7 / 10;
    let py_loc = loc - rust_loc;

    let rust_dir = root.join("src");
    let py_dir = root.join("py");
    std::fs::create_dir_all(&rust_dir).expect("rust fixture dir");
    std::fs::create_dir_all(&py_dir).expect("python fixture dir");

    const RUST_PER_FILE: usize = 1000; // 100 fns × 10 lines
    let rust_files = rust_loc.div_ceil(RUST_PER_FILE);
    let mut written_rust = 0usize;
    for file in 0..rust_files {
        let mut src = String::with_capacity(RUST_PER_FILE * 70);
        src.push_str("// fixture module generated by the REQ-CK-002 bench\n");
        for i in 0..100 {
            let f = file * 100 + i;
            let (call, ret) = if i < 99 {
                (
                    format!("    let next = f_{}();", f + 1),
                    "    next + 1\n".to_string(),
                )
            } else {
                (
                    "    let next = 0u64;".to_string(),
                    "    next + 1\n".to_string(),
                )
            };
            src.push_str(&format!(
                "/// Compute a synthetic value for fixture function {f}.\npub fn f_{f}() -> u64 {{\n    let base = {f}u64 % 7;\n    if base > 3 {{\n        return base;\n    }}\n{call}\n    {ret}}}\n\n"
            ));
        }
        std::fs::write(rust_dir.join(format!("m{file}.rs")), &src).expect("rust fixture file");
        written_rust += src.lines().count();
    }

    const PY_PER_FILE: usize = 800; // 100 fns × 8 lines
    let py_files = py_loc.div_ceil(PY_PER_FILE);
    let mut written_py = 0usize;
    for file in 0..py_files {
        let mut src = String::with_capacity(PY_PER_FILE * 60);
        src.push_str("# fixture module generated by the REQ-CK-002 bench\n");
        for i in 0..100 {
            let f = file * 100 + i;
            if i < 99 {
                src.push_str(&format!(
                    "def f_{f}():\n    \"\"\"Synthetic fixture function {f}.\"\"\"\n    base = {f} % 7\n    total = base + 1\n    if base > 3:\n        return base\n    return f_{}()\n\n",
                    f + 1
                ));
            } else {
                src.push_str(&format!(
                    "def f_{f}():\n    \"\"\"Synthetic fixture function {f}.\"\"\"\n    base = {f} % 7\n    total = base + 1\n    if base > 3:\n        return base\n    return total\n\n"
                ));
            }
        }
        std::fs::write(py_dir.join(format!("m{file}.py")), &src).expect("python fixture file");
        written_py += src.lines().count();
    }

    (written_rust, written_py)
}

fn bench_code_index(c: &mut Criterion) {
    let loc = bench_loc();
    let ts = TempStore::new();
    let root = ts.root().to_path_buf();
    let ctx = ts.ctx();
    let repo = tempfile::tempdir().expect("fixture repo");
    let (rust_loc, py_loc) = write_fixture(repo.path(), loc);

    let rt = tokio::runtime::Runtime::new().expect("bench tokio runtime");
    let index = rt
        .block_on(OkfIndex::open(&ctx, &root, None))
        .expect("okf index opens");

    // Warm-up pass: one full cold index of the fresh fixture (mirror
    // semantics are replace-per-project, so re-indexing is safe). This
    // warms OS file caches and page tables — the measured run below is the
    // pipeline on warm caches, exactly like criterion's own warm-up phase.
    // The cold-cache cost is reported, not hidden.
    let warm_start = Instant::now();
    rt.block_on(index.index_project(&ctx, repo.path()))
        .expect("warm-up index succeeds");
    let warmup_ms = warm_start.elapsed().as_secs_f64() * 1e3;

    // Cold index (REQ-CK-002): the measured operation. `IndexReport`
    // carries the crate's own wall-clock timing.
    let start = Instant::now();
    let result = rt
        .block_on(index.index_project(&ctx, repo.path()))
        .expect("fixture indexes");
    let wall_ms = start.elapsed().as_secs_f64() * 1e3;

    report(
        "gate_code_index",
        json!({
            "loc": loc,
            "rust_loc": rust_loc,
            "py_loc": py_loc,
            "index_ms": result.duration_ms,
            "wall_ms": wall_ms,
            "warmup_ms_cold_cache": warmup_ms,
            "files_scanned": result.files_scanned,
            "files_indexed": result.files_indexed,
            "concept_count": result.concept_count,
            "symbol_count": result.symbol_count,
            "graph_nodes": result.graph_node_count,
            "graph_edges": result.graph_edge_count,
            "budget_10k_ms": 2000,
            "budget_100k_ms": 30000,
            "expected_100k_window_ms": [10000, 30000],
        }),
    );

    // Criterion: L4 overview latency (REQ-CK-003 ~100 ms order of
    // magnitude) — the only cheap op worth a full distribution.
    let mut group = c.benchmark_group("code");
    group.sample_size(30);
    group.bench_function("project_overview", |b| {
        b.iter(|| {
            let overview = rt.block_on(index.project_overview(&ctx, &result.project_id));
            std::hint::black_box(overview.expect("overview serves"))
        })
    });
    group.finish();
}

criterion_group!(benches, bench_code_index);
criterion_main!(benches);
