//! Server handler + tool registry assembly (T-071, REQ-MS-002/003/005).
//!
//! The 15 tools are defined as `#[tool]` methods in [`crate::tools_memory`]
//! (7) and [`crate::tools_code`] (8); the `#[tool_router]` macro generates
//! a `ToolRouter` constructor per impl block, and this module combines them
//! into the final registry and implements [`ServerHandler`]:
//!
//! * `get_info` — tools capability (REQ-MS-002);
//! * `list_tools` — the registry, sorted by name (REQ-MS-002 scenario);
//! * `call_tool` — dispatch through the router (unknown tools and
//!   schema-violating parameters surface as structured errors, REQ-MS-005);
//! * `get_tool` — single-tool lookup for the SDK's pre-call validation.

use std::future::Future;

use memento_i18n::strings::{StringKey, es};
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::tool::ToolCallContext;
use rmcp::model::{
    CallToolRequestParams, CallToolResponse, ListToolsResult, PaginatedRequestParams,
    ServerCapabilities, ServerInfo, Tool,
};
use rmcp::service::{MaybeSendFuture, RequestContext, RoleServer};
use rmcp::{ErrorData, ServerHandler};

use crate::McpServer;

/// Assemble the full 15-tool registry (REQ-MS-002): 7 `memory.*` tools +
/// 8 `code.*` tools. Both halves are generated by `#[tool_router]` in the
/// tool modules; `+` merges them.
///
/// The `#[tool]` macro only accepts literal descriptions, so the bilingual
/// strings are stamped here from the memento-i18n ES-first tables — the
/// single source of truth for user-facing text (REQ-MS-004).
pub fn tool_router() -> ToolRouter<McpServer> {
    let mut router = McpServer::memory_tools() + McpServer::code_tools();
    for route in router.map.values_mut() {
        let description = match route.attr.name.as_ref() {
            "memory.search" => es(StringKey::McpToolSearchDesc),
            "memory.ingest_text" => es(StringKey::McpToolIngestTextDesc),
            "memory.ingest_document" => es(StringKey::McpToolIngestDocumentDesc),
            "memory.get_chunk" => es(StringKey::McpToolGetChunkDesc),
            "memory.feedback" => es(StringKey::McpToolFeedbackDesc),
            "memory.delete" => es(StringKey::McpToolDeleteDesc),
            "memory.context_fit" => es(StringKey::McpToolContextFitDesc),
            "code.project_overview" => es(StringKey::CodeToolProjectOverviewDesc),
            "code.symbol_lookup" => es(StringKey::CodeToolSymbolLookupDesc),
            "code.callers_of" => es(StringKey::CodeToolCallersOfDesc),
            "code.callees_of" => es(StringKey::CodeToolCalleesOfDesc),
            "code.impact" => es(StringKey::CodeToolImpactDesc),
            "code.dependencies" => es(StringKey::CodeToolDependenciesDesc),
            "code.search" => es(StringKey::CodeToolSearchDesc),
            "code.graph_dump" => es(StringKey::CodeToolGraphDumpDesc),
            _ => continue,
        };
        route.attr.description = Some(description.into());
    }
    router
}

impl ServerHandler for McpServer {
    /// Server identity: tools only (prompts/resources are non-goals).
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
    }

    /// Dispatch a `tools/call` through the registry (REQ-MS-005: unknown
    /// tools and bad parameters are structured errors; the session stays
    /// alive — the router never terminates the transport).
    fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<RoleServer>,
    ) -> impl Future<Output = Result<CallToolResponse, ErrorData>> + MaybeSendFuture + '_ {
        let router = self.router.clone();
        async move {
            router
                .call(ToolCallContext::new(self, request, context))
                .await
        }
    }

    /// Serve the registry, sorted by tool name (REQ-MS-002).
    fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> impl Future<Output = Result<ListToolsResult, ErrorData>> + MaybeSendFuture + '_ {
        let tools = self.router.list_all();
        async move {
            Ok(ListToolsResult {
                tools,
                ..Default::default()
            })
        }
    }

    /// Single-tool lookup (the SDK uses it for pre-call validation).
    fn get_tool(&self, name: &str) -> Option<Tool> {
        self.router.get(name).cloned()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::McpServer;
    use memento_application::{AppService, SystemClock};
    use memento_parse::ParseService;
    use memento_parse::anydoc::{AnydocCommand, AnydocConfig};
    use memento_testkit::{StubEmbedPort, TempStore};
    use rmcp::model::ServerCapabilities;
    use serde_json::Value;
    use std::sync::Arc;
    use std::time::Duration;

    async fn test_server(ts: &TempStore) -> McpServer {
        let app = AppService::open(
            &ts.ctx(),
            ts.root(),
            Arc::new(ParseService::new(AnydocConfig {
                command: AnydocCommand {
                    program: "never-invoked".into(),
                    args: vec![],
                    env: vec![],
                },
                timeout: Duration::from_secs(1),
                stdout_limit: 1024,
                staging_dir: std::env::temp_dir(),
            })),
            Some(Arc::new(StubEmbedPort::default())),
            Arc::new(SystemClock),
        )
        .await
        .expect("test app opens");
        McpServer::from_app(app, ts.ctx(), memento_i18n::Locale::Es)
    }

    #[tokio::test]
    async fn registry_has_exactly_the_15_spec_tools() {
        // REQ-MS-002: tools/list must expose every MVP-surface tool with
        // JSON-schema parameters.
        let ts = TempStore::new();
        let server = test_server(&ts).await;
        let tools = server.router().list_all();

        let names: Vec<&str> = tools.iter().map(|t| t.name.as_ref()).collect();
        let expected = [
            "memory.search",
            "memory.ingest_text",
            "memory.ingest_document",
            "memory.get_chunk",
            "memory.feedback",
            "memory.delete",
            "memory.context_fit",
            "code.project_overview",
            "code.symbol_lookup",
            "code.callers_of",
            "code.callees_of",
            "code.impact",
            "code.dependencies",
            "code.search",
            "code.graph_dump",
        ];
        assert_eq!(names.len(), 15, "exactly 15 tools: {names:?}");
        for name in expected {
            assert!(names.contains(&name), "missing {name}: {names:?}");
        }

        // Every tool carries a bilingual description (ES primary) and an
        // input schema with root type object.
        for tool in &tools {
            let desc = tool
                .description
                .as_deref()
                .expect("tool description present (REQ-MS-004)");
            assert!(!desc.is_empty(), "{}: description non-empty", tool.name);
            assert_eq!(
                tool.input_schema.get("type").and_then(Value::as_str),
                Some("object"),
                "{}: input schema root type object",
                tool.name
            );
        }

        // Capabilities advertise tools.
        let info = server.get_info();
        assert!(
            info.capabilities.tools.is_some(),
            "tools capability advertised (REQ-MS-002)"
        );
    }

    #[test]
    fn server_refuses_to_start_without_credentials() {
        // REQ-MS-003 scenario "Unauthenticated startup": with no
        // MEMENTO_TOKEN the server refuses to serve — the context
        // resolution fails before any tool can be called.
        static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
        let _guard = ENV_LOCK.lock().unwrap();

        unsafe {
            std::env::remove_var("MEMENTO_TOKEN");
            std::env::remove_var("MEMENTO_AGENT_ID");
        }
        let root = tempfile::tempdir().expect("tempdir");
        let err = McpServer::resolve_startup_context(root.path()).expect_err("must refuse");
        assert_eq!(err.code(), "AUTH_FAILED", "uniform auth error (REQ-TA-006)");
    }

    #[test]
    fn server_refuses_without_agent_id() {
        // REQ-TA-003: MEMENTO_AGENT_ID is mandatory too — a token without
        // an agent identity must not bind a context.
        static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
        let _guard = ENV_LOCK.lock().unwrap();

        unsafe {
            std::env::remove_var("MEMENTO_TOKEN");
            std::env::remove_var("MEMENTO_AGENT_ID");
            std::env::set_var("MEMENTO_TOKEN", "memo_bogus-bogus-bogus");
        }
        let root = tempfile::tempdir().expect("tempdir");
        let err = McpServer::resolve_startup_context(root.path()).expect_err("must refuse");
        assert_eq!(err.code(), "INVALID_INPUT", "agent id variable named");
    }

    #[tokio::test]
    async fn capabilities_are_tools_only() {
        // MVP non-goals: no prompts/resources/logging/completions.
        let ts = TempStore::new();
        let server = test_server(&ts).await;
        let info = server.get_info();
        assert!(info.capabilities.prompts.is_none());
        assert!(info.capabilities.resources.is_none());
        let _ = ServerCapabilities::builder().enable_tools().build();
    }
}
