//! Server handler + tool registry assembly (T-071, REQ-MS-002/003/005).
//!
//! The 15 tools are defined as `#[tool]` methods in [`crate::tools_memory`]
//! (7) and [`crate::tools_code`] (8); the `#[tool_router]` macro generates
//! a `ToolRouter` constructor per impl block, and this module combines them
//! into the final registry and implements [`ServerHandler`]:
//!
//! * `get_info` — tools capability (REQ-MS-002);
//! * `list_tools` — the registry, sorted by name (REQ-MS-002 scenario);
//! * `call_tool` — dispatch through the router (unknown tools and
//!   schema-violating parameters surface as structured errors, REQ-MS-005);
//! * `get_tool` — single-tool lookup for the SDK's pre-call validation.

use std::future::Future;
use std::time::Duration;

use memento_i18n::strings::{StringKey, es};
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::tool::ToolCallContext;
use rmcp::model::{
    CallToolRequestParams, CallToolResponse, ListToolsResult, PaginatedRequestParams,
    ServerCapabilities, ServerInfo, Tool,
};
use rmcp::service::{MaybeSendFuture, RequestContext, RoleServer};
use rmcp::{ErrorData, ServerHandler};
use tracing::Instrument;

use crate::McpServer;

/// Per-tool slow-call warn threshold (REQ-OBS-005, design D4): 30s.
const TOOL_WARN_THRESHOLD: Duration = Duration::from_secs(30);

/// Log the >30s warn for a tool call (REQ-OBS-005, detect-only — deadlock
/// fixing is out of scope). The threshold is a parameter so tests inject it
/// without sleeping 30s; production passes [`TOOL_WARN_THRESHOLD`].
fn warn_if_slow(tool: &str, elapsed: Duration, threshold: Duration) {
    if elapsed > threshold {
        tracing::warn!(
            tool = %tool,
            elapsed_s = elapsed.as_secs_f64(),
            "mcp tool call exceeded the 30s threshold"
        );
    }
}

/// Assemble the full 15-tool registry (REQ-MS-002): 7 `memory.*` tools +
/// 8 `code.*` tools. Both halves are generated by `#[tool_router]` in the
/// tool modules; `+` merges them.
///
/// The `#[tool]` macro only accepts literal descriptions, so the bilingual
/// strings are stamped here from the memento-i18n ES-first tables — the
/// single source of truth for user-facing text (REQ-MS-004).
pub fn tool_router() -> ToolRouter<McpServer> {
    let mut router = McpServer::memory_tools() + McpServer::code_tools();
    for route in router.map.values_mut() {
        let description = match route.attr.name.as_ref() {
            "memory.search" => es(StringKey::McpToolSearchDesc),
            "memory.ingest_text" => es(StringKey::McpToolIngestTextDesc),
            "memory.ingest_document" => es(StringKey::McpToolIngestDocumentDesc),
            "memory.get_chunk" => es(StringKey::McpToolGetChunkDesc),
            "memory.feedback" => es(StringKey::McpToolFeedbackDesc),
            "memory.delete" => es(StringKey::McpToolDeleteDesc),
            "memory.context_fit" => es(StringKey::McpToolContextFitDesc),
            "code.project_overview" => es(StringKey::CodeToolProjectOverviewDesc),
            "code.symbol_lookup" => es(StringKey::CodeToolSymbolLookupDesc),
            "code.callers_of" => es(StringKey::CodeToolCallersOfDesc),
            "code.callees_of" => es(StringKey::CodeToolCalleesOfDesc),
            "code.impact" => es(StringKey::CodeToolImpactDesc),
            "code.dependencies" => es(StringKey::CodeToolDependenciesDesc),
            "code.search" => es(StringKey::CodeToolSearchDesc),
            "code.graph_dump" => es(StringKey::CodeToolGraphDumpDesc),
            _ => continue,
        };
        route.attr.description = Some(description.into());
    }
    router
}

impl ServerHandler for McpServer {
    /// Server identity: tools only (prompts/resources are non-goals).
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
    }

    /// Dispatch a `tools/call` through the registry (REQ-MS-005: unknown
    /// tools and bad parameters are structured errors; the session stays
    /// alive — the router never terminates the transport).
    fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<RoleServer>,
    ) -> impl Future<Output = Result<CallToolResponse, ErrorData>> + MaybeSendFuture + '_ {
        let router = self.router.clone();
        async move {
            // REQ-OBS-005: every tool call runs inside a per-tool span with
            // elapsed timing; calls beyond TOOL_WARN_THRESHOLD log a warn
            // naming the tool and the elapsed seconds (detect-only).
            let tool = request.name.to_string();
            let span = tracing::info_span!("mcp_tool", tool = %tool);
            let start = std::time::Instant::now();
            let result = router
                .call(ToolCallContext::new(self, request, context))
                .instrument(span)
                .await;
            warn_if_slow(&tool, start.elapsed(), TOOL_WARN_THRESHOLD);
            result
        }
    }

    /// Serve the registry, sorted by tool name (REQ-MS-002).
    fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> impl Future<Output = Result<ListToolsResult, ErrorData>> + MaybeSendFuture + '_ {
        let tools = self.router.list_all();
        async move {
            Ok(ListToolsResult {
                tools,
                ..Default::default()
            })
        }
    }

    /// Single-tool lookup (the SDK uses it for pre-call validation).
    fn get_tool(&self, name: &str) -> Option<Tool> {
        self.router.get(name).cloned()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::McpServer;
    use memento_application::{AppService, SystemClock};
    use memento_parse::ParseService;
    use memento_parse::anydoc::{AnydocCommand, AnydocConfig};
    use memento_testkit::{StubEmbedPort, TempStore};
    use rmcp::model::ServerCapabilities;
    use serde_json::Value;
    use std::sync::{Arc, Mutex};
    use std::time::Duration;

    async fn test_server(ts: &TempStore) -> McpServer {
        let app = AppService::open(
            &ts.ctx(),
            ts.root(),
            Arc::new(ParseService::new(AnydocConfig {
                command: AnydocCommand {
                    program: "never-invoked".into(),
                    args: vec![],
                    env: vec![],
                },
                timeout: Duration::from_secs(1),
                stdout_limit: 1024,
                staging_dir: std::env::temp_dir(),
            })),
            Some(Arc::new(StubEmbedPort::default())),
            Arc::new(SystemClock),
        )
        .await
        .expect("test app opens");
        McpServer::from_app(app, ts.ctx(), memento_i18n::Locale::Es)
    }

    #[tokio::test]
    async fn registry_has_exactly_the_15_spec_tools() {
        // REQ-MS-002: tools/list must expose every MVP-surface tool with
        // JSON-schema parameters.
        let ts = TempStore::new();
        let server = test_server(&ts).await;
        let tools = server.router().list_all();

        let names: Vec<&str> = tools.iter().map(|t| t.name.as_ref()).collect();
        let expected = [
            "memory.search",
            "memory.ingest_text",
            "memory.ingest_document",
            "memory.get_chunk",
            "memory.feedback",
            "memory.delete",
            "memory.context_fit",
            "code.project_overview",
            "code.symbol_lookup",
            "code.callers_of",
            "code.callees_of",
            "code.impact",
            "code.dependencies",
            "code.search",
            "code.graph_dump",
        ];
        assert_eq!(names.len(), 15, "exactly 15 tools: {names:?}");
        for name in expected {
            assert!(names.contains(&name), "missing {name}: {names:?}");
        }

        // Every tool carries a bilingual description (ES primary) and an
        // input schema with root type object.
        for tool in &tools {
            let desc = tool
                .description
                .as_deref()
                .expect("tool description present (REQ-MS-004)");
            assert!(!desc.is_empty(), "{}: description non-empty", tool.name);
            assert_eq!(
                tool.input_schema.get("type").and_then(Value::as_str),
                Some("object"),
                "{}: input schema root type object",
                tool.name
            );
        }

        // Capabilities advertise tools.
        let info = server.get_info();
        assert!(
            info.capabilities.tools.is_some(),
            "tools capability advertised (REQ-MS-002)"
        );
    }

    #[test]
    fn server_refuses_to_start_without_credentials() {
        // REQ-MS-003 scenario "Unauthenticated startup": with no
        // MEMENTO_TOKEN the server refuses to serve — the context
        // resolution fails before any tool can be called.
        static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
        let _guard = ENV_LOCK.lock().unwrap();

        unsafe {
            std::env::remove_var("MEMENTO_TOKEN");
            std::env::remove_var("MEMENTO_AGENT_ID");
        }
        let root = tempfile::tempdir().expect("tempdir");
        let err = McpServer::resolve_startup_context(root.path()).expect_err("must refuse");
        assert_eq!(err.code(), "AUTH_FAILED", "uniform auth error (REQ-TA-006)");
    }

    #[test]
    fn server_refuses_without_agent_id() {
        // REQ-TA-003: MEMENTO_AGENT_ID is mandatory too — a token without
        // an agent identity must not bind a context.
        static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
        let _guard = ENV_LOCK.lock().unwrap();

        unsafe {
            std::env::remove_var("MEMENTO_TOKEN");
            std::env::remove_var("MEMENTO_AGENT_ID");
            std::env::set_var("MEMENTO_TOKEN", "memo_bogus-bogus-bogus");
        }
        let root = tempfile::tempdir().expect("tempdir");
        let err = McpServer::resolve_startup_context(root.path()).expect_err("must refuse");
        assert_eq!(err.code(), "INVALID_INPUT", "agent id variable named");
    }

    #[tokio::test]
    async fn capabilities_are_tools_only() {
        // MVP non-goals: no prompts/resources/logging/completions.
        let ts = TempStore::new();
        let server = test_server(&ts).await;
        let info = server.get_info();
        assert!(info.capabilities.prompts.is_none());
        assert!(info.capabilities.resources.is_none());
        let _ = ServerCapabilities::builder().enable_tools().build();
    }

    // ---- REQ-OBS-005: per-tool span + >30s warn -----------------------------

    /// Writes tracing output into a shared buffer (fmt JSON writer).
    struct SharedWriter(Arc<Mutex<Vec<u8>>>);

    impl std::io::Write for SharedWriter {
        fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
            self.0.lock().expect("buffer lock").extend_from_slice(buf);
            Ok(buf.len())
        }
        fn flush(&mut self) -> std::io::Result<()> {
            Ok(())
        }
    }

    /// Run a synchronous body under a fmt-JSON subscriber (TLS default) and
    /// return every emitted event, parsed.
    fn capture_sync<F: FnOnce()>(body: F) -> Vec<Value> {
        let buf: Arc<Mutex<Vec<u8>>> = Arc::new(Mutex::new(Vec::new()));
        let sub = tracing_subscriber::fmt()
            .with_ansi(false)
            .with_writer({
                let buf = buf.clone();
                move || SharedWriter(buf.clone())
            })
            .json()
            .finish();
        tracing::subscriber::with_default(sub, body);
        let out = String::from_utf8(buf.lock().expect("buffer lock").clone()).expect("utf8");
        out.lines()
            .filter_map(|line| serde_json::from_str(line).ok())
            .collect()
    }

    #[test]
    fn slow_tool_call_warns_with_tool_and_elapsed() {
        // REQ-OBS-005: a call beyond the 30s threshold logs a warn carrying
        // the tool name and the elapsed seconds. The threshold is injected
        // so the decision is testable without sleeping 31s.
        let events = capture_sync(|| {
            warn_if_slow("test.slow", Duration::from_secs(31), TOOL_WARN_THRESHOLD);
        });
        let warns: Vec<&Value> = events.iter().filter(|v| v["level"] == "WARN").collect();
        assert_eq!(warns.len(), 1, "one warn emitted: {events:?}");
        assert_eq!(warns[0]["fields"]["tool"], "test.slow", "tool named");
        let elapsed = warns[0]["fields"]["elapsed_s"]
            .as_f64()
            .expect("elapsed_s recorded");
        assert!(elapsed > 30.0, "elapsed seconds: {elapsed}");
    }

    #[test]
    fn fast_tool_call_emits_no_warn() {
        // REQ-OBS-005: below the threshold → silent (detect-only, no
        // false positives on healthy calls).
        let events = capture_sync(|| {
            warn_if_slow("test.slow", Duration::from_secs(29), TOOL_WARN_THRESHOLD);
        });
        assert!(
            events.iter().all(|v| v["level"] != "WARN"),
            "no warn below threshold: {events:?}"
        );
    }

    #[tokio::test]
    async fn tool_call_runs_inside_mcp_tool_span() {
        // REQ-OBS-005: every tool call opens a per-tool span carrying the
        // tool name; a fast call (fake slow tool sleeping 20ms) emits no
        // warn and the tool result is returned unchanged. Served through the
        // real in-process client pair so the full dispatch path runs — the
        // server future polls on a spawned task, so capture must be global.
        use rmcp::handler::server::router::tool::ToolRoute;
        use rmcp::model::{CallToolRequestParams, CallToolResult, Tool};
        use rmcp::{ClientHandler, ServiceExt};
        use std::borrow::Cow;

        struct TestClient;
        impl ClientHandler for TestClient {}

        let ts = TempStore::new();
        let mut server = test_server(&ts).await;
        let attr = Tool::new(
            "test.slow",
            "fake slow tool for REQ-OBS-005",
            serde_json::json!({"type": "object"})
                .as_object()
                .cloned()
                .expect("object schema"),
        );
        server.router.map.insert(
            Cow::Borrowed("test.slow"),
            ToolRoute::new_dyn(attr, |_ctx| {
                Box::pin(async {
                    tokio::time::sleep(Duration::from_millis(20)).await;
                    Ok(CallToolResult::success(vec![]).into())
                })
            }),
        );

        let buf: Arc<Mutex<Vec<u8>>> = Arc::new(Mutex::new(Vec::new()));
        let sub = tracing_subscriber::fmt()
            .with_span_events(tracing_subscriber::fmt::format::FmtSpan::FULL)
            .with_ansi(false)
            .with_writer({
                let buf = buf.clone();
                move || SharedWriter(buf.clone())
            })
            .json()
            .finish();
        let _ = tracing::subscriber::set_global_default(sub);

        let (server_half, client_half) = tokio::io::duplex(1 << 20);
        let _task = tokio::spawn(async move {
            let running = server.serve(server_half).await.expect("server handshake");
            let _ = running.waiting().await;
        });
        let client = TestClient
            .serve(client_half)
            .await
            .expect("client handshake");

        let res = client
            .call_tool(CallToolRequestParams::new("test.slow"))
            .await
            .expect("tool call");
        assert!(
            res.content.is_empty(),
            "fake tool result returned unchanged"
        );

        let out = String::from_utf8(buf.lock().expect("buffer lock").clone()).expect("utf8");
        let lines: Vec<Value> = out
            .lines()
            .filter_map(|line| serde_json::from_str(line).ok())
            .collect();
        let opens: Vec<&Value> = lines
            .iter()
            .filter(|v| v["span"]["name"] == "mcp_tool" && v["fields"]["message"] == "new")
            .collect();
        assert_eq!(opens.len(), 1, "one mcp_tool span opens: {lines:?}");
        assert_eq!(
            opens[0]["span"]["tool"], "test.slow",
            "tool name on the span"
        );
        assert!(
            lines.iter().all(|v| v["level"] != "WARN"),
            "fast call emits no warn: {lines:?}"
        );
    }
}
